### ISSUE TITLE
Vertical Alignment

### ISSUE THREAD

**Issue by oobbles** [oobbles/customer_screen#1]
<img width="1421" alt="screen shot 2015-08-18 at 11 31 00 am" src="https://cloud.githubusercontent.com/assets/2162883/9335990/c3eea660-459c-11e5-8ed5-fa157973c7c0.png">
I changed from floating elements to the grid/span combo but now the vertical alignment is not right.  Things are getting pushy on to the elements below.  For instance, the date entered box is pushing down in to my next grid section.  I'm wondering if I have to wrap yet another div around each div grid grouping to make some type of space around them?  
I tried putting each section in another div, playing with both padding and margin, and still having issues.

**Comment by sumeetjain** [comment]
Can you link me to the code? This sounds like an issue caused be floats not being cleared, so I'd like to take a look.

**Comment by oobbles** [comment]
https://github.com/oobbles/customer_screen/blob/master/tet.html

**Comment by oobbles** [comment]
Line 182.  That code does not have my extra practice divs.

**Comment by sumeetjain** [comment]
It's hard to read that code. It's all commented out, and there are a number of indentation issues.

Especially for something like this issue, where the cause could very easily be an unclosed div or the absence of a clearing div, proper indentation is vital. I'll take a look after you fix the code formatting. And please don't comment it out – it removes the syntax highlighting, which makes it hard to read.

**Comment by sumeetjain** [comment]
I would expect each section of elements that you want as a partial column to be wrapped by a div with `span-1` (for example). And those `span-1` divs would be wrapper by a div with `grid-2` (for example). I don't see that in place for your implementation.

I see this:

``` html
<input type="checkbox" id="test_checkbox_1" name="test_checkbox_1" />
            <label for="test_checkbox_1">Active</label>
            <span style="float: right">
                <label for="date"> Date Entered</label>
                <input type="date" id="date" name="date" />
            </span>
            <br />
            <input type="checkbox" id="test_checkbox_2" name="test_checkbox_2" />
            <label for="test_checkbox_2">PO Required</label>
            <br />
```

I expected this:

``` html
<div class="grid-2">
  <div class="span-1">
    stuff for left column
  </div>

  <div class="span-1">
    stuff for right column
  </div>
</div>
```

**Comment by oobbles** [comment]
Solved:  Use grid forms within grid forms for proper spacing.
